# Generated by Django 4.0.8 on 2023-02-04 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orchestrator.organisation'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='account',
            field=models.ForeignKey(help_text='WHich accounts is used to connect to the service?', max_length=10, on_delete=django.db.models.deletion.PROTECT, to='orchestrator.account'),
        ),
    ]
