# Generated by Django 4.0.8 on 2023-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='data_type',
            field=models.CharField(choices=[('str', 'STR'), ('int', 'INT'), ('float', 'FLOAT'), ('list', 'LIST'), ('Dictionary', 'DICT'), ('bool', 'BOOL')], max_length=10, verbose_name='value data type'),
        ),
    ]
