# Generated by Django 4.0.8 on 2023-02-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_customer_organisation_alter_pipeline_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.CharField(blank=True, help_text='A description for the Component.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.CharField(blank=True, help_text='A description for the Feature.', max_length=255, null=True),
        ),
    ]
