# Generated by Django 4.0.8 on 2023-02-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0006_alter_gitrepo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='source_type',
            field=models.CharField(choices=[('tf_cloud', 'TF Cloud'), ('codepipeline', 'CodePipeline'), ('mobile_build', 'Mobile Build'), ('local_build', 'Local Build')], help_text='Indicates the type of pipeline source.', max_length=20, verbose_name='Source Type'),
        ),
    ]
