# Generated by Django 4.0.8 on 2023-02-06 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0007_alter_pipeline_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='orchestrator.project'),
        ),
    ]
