# Generated by Django 4.0.8 on 2023-02-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0008_alter_pipeline_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfiguration',
            name='features',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
