# Generated by Django 4.0.8 on 2023-02-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0009_remove_projectconfiguration_features_delete_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepo',
            name='state',
            field=models.CharField(default='new', help_text='Internal state of the local_url', max_length=16, verbose_name='Repo State'),
        ),
    ]
