# Generated by Django 4.0.8 on 2023-02-10 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0010_gitrepo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='account',
            field=models.ForeignKey(help_text='WHich accounts is used to connect to the service?', max_length=10, on_delete=django.db.models.deletion.PROTECT, related_name='pipeline', to='orchestrator.account'),
        ),
    ]
