# Generated by Django 4.0.8 on 2023-02-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0011_alter_pipeline_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='key',
            field=models.CharField(help_text='The key of the setting.', max_length=255, unique=True),
        ),
    ]
