# Generated by Django 4.0.8 on 2023-02-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0012_alter_settings_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepo',
            name='local_url',
            field=models.CharField(blank=True, default='', help_text='URL of the repository.', max_length=255, verbose_name='temp dir'),
        ),
    ]
