# Changes here will be overwritten by Copier
_commit: d66427b
_src_path: /Users/enigma/Projects/GeneratedProjects/orchestrator
component: backend
module_name: orchestrator
project_name: devportaldevportal
